apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: outfit-combine
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: outfit_combine
  DB_USER: outfit_user
  KEYCLOAK_ISSUER_URI: https://auth.YOURDOMAIN.com/realms/outfit-combine
  KEYCLOAK_JWK_SET_URI: http://keycloak-service:8080/realms/outfit-combine/protocol/openid-connect/certs
  MINIO_ENDPOINT: http://minio-service:9000
  MINIO_BUCKET: outfit-combine
  MINIO_PUBLIC_URL: https://files.YOURDOMAIN.com
  CORS_ALLOWED_ORIGINS: https://YOURDOMAIN.com
  SPRING_PROFILES_ACTIVE: prod
  ANTHROPIC_MODEL: claude-sonnet-4-6
  ANTHROPIC_BASE_URL: https://api.anthropic.com
  OPENWEATHERMAP_BASE_URL: https://api.openweathermap.org
