apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: outfit-combine
data:
  KC_DB: postgres
  KC_DB_URL: jdbc:postgresql://postgres-service:5432/outfit_combine
  KC_DB_USERNAME: outfit_user
  KC_HTTP_ENABLED: "true"
  KC_PROXY: edge
  KC_HOSTNAME_STRICT: "true"
