apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: outfit-combine
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.6-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: outfit_combine
            - name: POSTGRES_USER
              value: outfit_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 512Mi
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "outfit_user", "-d", "outfit_combine"]
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
